### PR TITLE
feat: add project schema

### PR DESCRIPTION
**Pull request by Amrawy98**
# Description

* refactored resolvers and typedef in workspace
  * removed inputs of type workspace and replaced it with only needed data
* added typedefs and resolvers for project
* changed a variable name in item typedefs and resolvers from itemID to itemId 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

* get project by id
Screenshot 2021-09-10 203856

* Create project
Screenshot 2021-09-10 204807

* Update project
Screenshot 2021-09-10 205233

* Delete project
Screenshot 2021-09-10 205407

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by akrabdev — DISMISSED** [review]
Consider adding userID as arguments  for relevant queries/mutations , until authorization is set. 

great work so far.

**Review by samydevv — DISMISSED** [review]
Great job 👏

**Comment by Amrawy98** [comment]
> Consider adding userID as arguments for relevant queries/mutations , until authorization is set.
> 
> great work so far.

Done thanks Akrab.

**Review by AhmadAssal — APPROVED** [review]
Great work as always @Amrawy98

**Review by akrabdev — APPROVED** [review]

**Pull request merged**
