### PR TITLE
feat: add commitlint and initialize project

### PR DESCRIPTION
**Pull request by raslan**
# Description

This initializes the repo with our commit linting, package and lock files and the pull request template.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

I ran a few tests locally with commitlint to make sure it's initialized and working properly to enforce proper commit style.

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings

## Non-applicable:
- I have commented my code, particularly in hard-to-understand areas
- I have made corresponding changes to the documentation
- I have added tests that prove my fix is effective or that my feature works
- New and existing unit tests pass locally with my changes
- Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by AhmedHassan97 — APPROVED** [review]
lgtm

**Review by AhmadNaderAdel — COMMENTED** [review]
Looks fine

**Review by AhmadNaderAdel — APPROVED** [review]

**Review by samydevv — APPROVED** [review]

**Review by akrabdev — APPROVED** [review]
Looks good

**Review by Amrawy98 — APPROVED** [review]
lgtm

**Pull request merged**
